name: Waka Readme

on:
  # Runs at 12:00 AM UTC every day
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime Readme Tool
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          # This hides the 'Projects' section while keeping languages and time
          SHOW_PROJECTS: false
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
