name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      # Step 1: Last 7 Days
      - name: Weekly Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_PROJECTS: false
          SECTION_NAME: waka_7
          TIME_RANGE: last_7_days

      # Step 2: Last 30 Days
      - name: Monthly Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_PROJECTS: false
          SECTION_NAME: waka_30
          TIME_RANGE: last_30_days

      # Step 3: All Time
      - name: All Time Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_PROJECTS: false
          SECTION_NAME: waka_all
          TIME_RANGE: all_time
